name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"    # 每 6 小时自动检查一次（推荐）
  workflow_dispatch:         # 允许手动触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}   # 只在 Fork 中运行

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          upstream_sync_repo: cmliu/edgetunnel
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
